language: java
env:
  global:
    - CODACY_PROJECT_TOKEN=e4dd4115dfd84ac29dec5d7313efb8c5
script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew uploadCoverageToCodacy
notifications:
  email: false