language: java
jdk:
  - oraclejdk8
env:
  global:
    secure: "j7R/rX6UKmfk5XfunqJJfqAHhpXsQ6HGALVxIPymZBz0RH2+dS1g6LjWhpcLT05TAl0RKrFCwcMZgH7DBnRFyjrpt4zjHdF2Nf8ftzFSCSLoHhR/EtNmdSZWBHBSZGrcxMrus1LLE41FmTaO+JQsEkiCw5N/CWyxy8daUWa1ZTFHSU5C9wbkwMua4ESoNE3HmxyjT4nEpPDPjQz33exMsy19LgKs4PzdOHQldOMfKKNVeYsHPPIQLMmBQNVV+aHEvTL392QiHu9MCiYjmP8h2JAvMZqZR2gpSaGeBNrwjU8Ss3D9H3tUMafNcJUlnZXLslqfZGuq/s9u2JTA9rlnR4XZtQ5pza7iqgb2gd6HGJkUPOSQjQtaQPZbZlJz0qq/m5NDtewXh26d4RkNgt2I5jnmoAVH8kbcFpwTETl74cFNlrVntB4PjkdYo0jRuXNSvRLntSnL/qEzR6fDEIp0xh9plZvL5f40txK73+0Kg7TLaR7aw9z3mNRrPBy8yPVQwDshi5uYM+gND52zugJulaEu0FPOF0zrmEMfS0CnI2N49wr4nv6l1L7/3xSeFWLlclfsCtXS7hLfEcmuBBdKoYiQos+W7Xcu4W6CtGv8Npof/68FqfLYddfzlGIAQmK6fv458mhp80OpTs07m5nkNSFJkOXxvBfBTqIZHKFYrcg="
script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew uploadCoverageToCodacy
notifications:
  email: false